apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{ include "mysql.labels" . | nindent 4 }}
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mysql-data"