apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-cluster.fullname" . }}-conf
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4}}
data:
  primary.cnf: |
    # Apply this config only on the primary node
    [mysqld]
    log-bin
  replica.cnf: |
    # Apply this config only on replicas
    [mysqld]
    super-read-only

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4}}
data:
  MYSQL_INNODB_BUFFER_POOL_SIZE: "120M"