apiVersion: v1
kind: Secret
metadata:
  name: "{{- include "mysql-cluster.fullname" .}}-{{.Values.secret.dockerConfig.name}}"
  labels:
    {{- include "mysql-cluster.labels" . | nindent 4}}

type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.secret.dockerConfig.dockerConfigJSON | quote}}


---
# TODO: MySQL root password